### ISSUE TITLE
 clang: error: no such file or directory: './maro/backends/backend.c'

### ISSUE THREAD

**Issue by clm971910** [microsoft/maro#207] opened 2020-12-08 09:12 UTC
## Description
Mac:    python setup.py build   

clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/yewang/.virtualenvs/maro/include -I/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c ./maro/backends/backend.c -o build/temp.macosx-10.12-x86_64-3.6/./maro/backends/backend.o
clang: error: no such file or directory: './maro/backends/backend.c'
clang: error: no input files
error: command 'clang' failed with exit status 1

## To Reproduce

1.
2.
3.

## Environment

- MARO version (e.g., v0.1.1a1):
- MARO scenario (`CIM`, `Citi Bike`):
- MARO component (`Simulation`, `RL`, `Distributed Training`):
- Orchestration platform (`GraSS on Azure`, `AKS on Azure`):
- How you installed MARO (`pip`, `source`):
- OS (`Linux`, `Windows`, `macOS`):
- Python version (`3.6`, `3.7`):
- Docker image (e.g., arthursjiang/maro:cpu[5f36ed]):
- CPU/GPU:
- Any other relevant information:

**Comment by chaosddp** [comment] 2020-12-08 10:47
Seems like cython files not compiled into c, please have a try with 'bash scripts/build_maro.sh' instead of build it manually.

**Comment by clm971910** [comment] 2020-12-10 02:51
> Seems like cython files not compiled into c, please have a try with 'bash scripts/build_maro.sh' instead of build it manually.

(maro) ali-6c96cfd90593:maro yewang$ sh scripts/build_maro.sh  
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: Cython==0.29.14 in /Users/yewang/.virtualenvs/maro/lib/python3.6/site-packages (from -r ./maro/requirements.build.txt (line 1)) (0.29.14)
Requirement already satisfied: numpy==1.19.1 in /Users/yewang/.virtualenvs/maro/lib/python3.6/site-packages (from -r ./maro/requirements.build.txt (line 2)) (1.19.1)
running build_ext
error: each element of 'ext_modules' option must be an Extension instance or 2-tuple

**Comment by chaosddp** [comment] 2020-12-10 03:44
@ArthurJiang @Jinyu-W Seems like we have sorted the import order in setup.py, it will cause the this issue, conflict between setuptools and cython, we have to keep original import order, we should ignore setup.py for isort. I will create a PR to fix it.

**Comment by chaosddp** [comment] 2020-12-10 04:38
@clm971910 What's the version of setuptools package your are using? Would you please help to try with PR #208 to see if it can fix   your issue, it would work according to https://github.com/pypa/setuptools/issues/309.

**Comment by ArthurJiang** [comment] 2020-12-10 06:05
@chaosddp I think we can ignore the setup.py for a quick fix, please follow up it, merge back to master.

**Comment by clm971910** [comment] 2020-12-10 06:28
> @clm971910 What's the version of setuptools package your are using? I have tried with several old versions (17, 18, 45) of setuptools, cannot reproduce the issue on mac. And would you please help to try with PR #208 to see if it can fix your issue, it would work according to [pypa/setuptools#309](https://github.com/pypa/setuptools/issues/309).

(maro) ali-6c96cfd90593:maro yewang$ pip show setuptools 
Name: setuptools
Version: 50.3.2
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /Users/yewang/.virtualenvs/maro/lib/python3.6/site-packages
Requires: 
Required-by: Sphinx, kiwisolver

**Comment by Jinyu-W** [comment] 2020-12-10 08:18
@clm971910  This problem is fixed in PR https://github.com/microsoft/maro/pull/208. Since we cannot reproduce this issue, please try the newest version again. Thanks!

**Comment by clm971910** [comment] 2020-12-10 08:21
@Jinyu-W thank you

**Comment by clm971910** [comment] 2020-12-10 10:11
python setup.py build 

is successed , thanks

**Comment by chaosddp** [comment] 2020-12-10 11:31
Thank you to confirm, I will close this issue.

**Closed** 2020-12-10 11:32 UTC
Labels: 🐛 bug
